create table if not exists public.ranking (
    id bigint generated by default as identity primary key,
    nome text not null,
    pontuacao integer not null default 0,
    musica text,
    modo text not null default 'livre',
    created_at timestamptz not null default now()
);

alter table public.ranking enable row level security;

drop policy if exists "ranking_select_public" on public.ranking;
create policy "ranking_select_public"
on public.ranking
for select
to anon
using (true);

drop policy if exists "ranking_insert_public" on public.ranking;
create policy "ranking_insert_public"
on public.ranking
for insert
to anon
with check (true);

alter table public.ranking
    add column if not exists nome text,
    add column if not exists pontuacao integer default 0,
    add column if not exists musica text,
    add column if not exists modo text default 'livre',
    add column if not exists created_at timestamptz default now();

update public.ranking
set pontuacao = 0
where pontuacao is null;

update public.ranking
set modo = 'livre'
where modo is null;

update public.ranking
set created_at = now()
where created_at is null;

alter table public.ranking
    alter column nome set not null,
    alter column pontuacao set not null,
    alter column pontuacao set default 0,
    alter column modo set not null,
    alter column modo set default 'livre',
    alter column created_at set not null,
    alter column created_at set default now();

create extension if not exists pgcrypto;

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'ranking'
          and column_name = 'id'
          and data_type = 'uuid'
    ) then
        execute 'alter table public.ranking alter column id set default gen_random_uuid()';
    end if;
end $$;

create table if not exists public.lyrics_cache (
    id bigint generated by default as identity primary key,
    cache_key text not null unique,
    titulo text,
    artista text,
    plain_lyrics text,
    synced_lyrics text,
    source text,
    updated_at timestamptz not null default now()
);

alter table public.lyrics_cache enable row level security;

drop policy if exists "lyrics_cache_select_public" on public.lyrics_cache;
create policy "lyrics_cache_select_public"
on public.lyrics_cache
for select
to anon
using (true);

drop policy if exists "lyrics_cache_insert_public" on public.lyrics_cache;
create policy "lyrics_cache_insert_public"
on public.lyrics_cache
for insert
to anon
with check (true);

drop policy if exists "lyrics_cache_update_public" on public.lyrics_cache;
create policy "lyrics_cache_update_public"
on public.lyrics_cache
for update
to anon
using (true)
with check (true);
