create table if not exists public.ranking (
    id bigint generated by default as identity primary key,
    nome text not null,
    pontuacao integer not null default 0,
    musica text,
    modo text not null default 'livre',
    created_at timestamptz not null default now()
);

alter table public.ranking enable row level security;

drop policy if exists "ranking_select_public" on public.ranking;
create policy "ranking_select_public"
on public.ranking
for select
to anon
using (true);

drop policy if exists "ranking_insert_public" on public.ranking;
create policy "ranking_insert_public"
on public.ranking
for insert
to anon
with check (true);
