create table if not exists public.ranking (
    id bigint generated by default as identity primary key,
    nome text not null,
    pontuacao integer not null default 0,
    musica text,
    modo text not null default 'livre',
    created_at timestamptz not null default now()
);

alter table public.ranking enable row level security;

drop policy if exists "ranking_select_public" on public.ranking;
create policy "ranking_select_public"
on public.ranking
for select
to anon
using (true);

drop policy if exists "ranking_insert_public" on public.ranking;
create policy "ranking_insert_public"
on public.ranking
for insert
to anon
with check (true);

alter table public.ranking
    add column if not exists nome text,
    add column if not exists pontuacao integer default 0,
    add column if not exists musica text,
    add column if not exists modo text default 'livre',
    add column if not exists created_at timestamptz default now();

update public.ranking
set pontuacao = 0
where pontuacao is null;

update public.ranking
set modo = 'livre'
where modo is null;

update public.ranking
set created_at = now()
where created_at is null;

alter table public.ranking
    alter column nome set not null,
    alter column pontuacao set not null,
    alter column pontuacao set default 0,
    alter column modo set not null,
    alter column modo set default 'livre',
    alter column created_at set not null,
    alter column created_at set default now();

create extension if not exists pgcrypto;

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'ranking'
          and column_name = 'id'
          and data_type = 'uuid'
    ) then
        execute 'alter table public.ranking alter column id set default gen_random_uuid()';
    end if;
end $$;

create table if not exists public.lyrics_cache (
    id bigint generated by default as identity primary key,
    cache_key text not null unique,
    titulo text,
    artista text,
    plain_lyrics text,
    synced_lyrics text,
    source text,
    updated_at timestamptz not null default now()
);

alter table public.lyrics_cache enable row level security;

drop policy if exists "lyrics_cache_select_public" on public.lyrics_cache;
create policy "lyrics_cache_select_public"
on public.lyrics_cache
for select
to anon
using (true);

drop policy if exists "lyrics_cache_insert_public" on public.lyrics_cache;
create policy "lyrics_cache_insert_public"
on public.lyrics_cache
for insert
to anon
with check (true);

drop policy if exists "lyrics_cache_update_public" on public.lyrics_cache;
create policy "lyrics_cache_update_public"
on public.lyrics_cache
for update
to anon
using (true)
with check (true);

create table if not exists public.lyrics_verified (
    id bigint generated by default as identity primary key,
    titulo text not null,
    artista text not null default '',
    titulo_norm text not null default '',
    artista_norm text not null default '',
    plain_lyrics text,
    synced_lyrics text,
    fonte text not null default 'manual',
    observacao text,
    ativo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.lyrics_verified
    add column if not exists titulo text,
    add column if not exists artista text default '',
    add column if not exists titulo_norm text default '',
    add column if not exists artista_norm text default '',
    add column if not exists plain_lyrics text,
    add column if not exists synced_lyrics text,
    add column if not exists fonte text default 'manual',
    add column if not exists observacao text,
    add column if not exists ativo boolean default true,
    add column if not exists created_at timestamptz default now(),
    add column if not exists updated_at timestamptz default now();

update public.lyrics_verified
set artista = ''
where artista is null;

update public.lyrics_verified
set titulo_norm = lower(trim(titulo))
where titulo_norm is null or titulo_norm = '';

update public.lyrics_verified
set artista_norm = lower(trim(artista))
where artista_norm is null or artista_norm = '';

update public.lyrics_verified
set fonte = 'manual'
where fonte is null;

update public.lyrics_verified
set ativo = true
where ativo is null;

update public.lyrics_verified
set created_at = now()
where created_at is null;

update public.lyrics_verified
set updated_at = now()
where updated_at is null;

alter table public.lyrics_verified
    alter column titulo set not null,
    alter column artista set not null,
    alter column artista set default '',
    alter column titulo_norm set not null,
    alter column titulo_norm set default '',
    alter column artista_norm set not null,
    alter column artista_norm set default '',
    alter column fonte set not null,
    alter column fonte set default 'manual',
    alter column ativo set not null,
    alter column ativo set default true,
    alter column created_at set not null,
    alter column created_at set default now(),
    alter column updated_at set not null,
    alter column updated_at set default now();

create unique index if not exists lyrics_verified_titulo_artista_idx
on public.lyrics_verified (titulo_norm, artista_norm);

alter table public.lyrics_verified enable row level security;

drop policy if exists "lyrics_verified_select_public" on public.lyrics_verified;
create policy "lyrics_verified_select_public"
on public.lyrics_verified
for select
to anon
using (true);

drop policy if exists "lyrics_verified_insert_public" on public.lyrics_verified;
create policy "lyrics_verified_insert_public"
on public.lyrics_verified
for insert
to anon
with check (true);

drop policy if exists "lyrics_verified_update_public" on public.lyrics_verified;
create policy "lyrics_verified_update_public"
on public.lyrics_verified
for update
to anon
using (true)
with check (true);
